#!/bin/bash -e

if ! git remote | grep -qx bert; then
    git remote add bert git@github.com:muennich/sxiv.git
fi

git fetch -p bert

old_base=$(git merge-base master bert/master)
new_base=$(git rev-parse bert/master)

if [[ "$old_base" == "$new_base" ]]; then
    printf '%s\n' "No new changes upstream" >&2
else
    # back up, since we are rewriting history
    git branch "$(date +%Y%m%d%H%M%S%N)"
    git rebase -r bert/master
fi
